### ISSUE TITLE
Master issue: Update deprecated `checkout.js` script

### ISSUE THREAD

**Issue by reykjalin** [woocommerce/woocommerce-gateway-paypal-express-checkout#626]
PayPal has announced that they will be deprecating the [`checkout.js` script](https://developer.paypal.com/docs/archive/checkout/) we use in [our code](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/9487b8d757cc2ea5f063bb7c534e198beaa5b651/includes/class-wc-gateway-ppec-cart-handler.php#L461). Their documentation includes [instructions on how to update our code base](https://developer.paypal.com/docs/checkout/reference/upgrade-integration/#6-fix-deprecations) to use their new SDK.

>If you are using a previous version of the PayPal Checkout integration, including custom buttons, full-page redirects, or `checkout.js`, PayPal recommends that you upgrade to the latest version of the integration.
>
> [Source](https://developer.paypal.com/docs/checkout/reference/).

As far as I can tell, PayPal have not specified a date for when the `checkout.js` script will no longer be available so I'm not sure how much time we have to update the script; I assume it's in the order of months.

>Checkout with `checkout.js`. Valid before February 2019. Customers who use `checkout.js` can access reference and support material in this Checkout guide. However, PayPal does not update `checkout.js` with new features and enhancements.
>
> [Source](https://developer.paypal.com/docs/archive/checkout/).

At the very least `checkout.js` will not be receiving any updates; it was archived in February 2019, almost 8 months ago.

This seems to at the very least change how smart buttons function [[#](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/622#issuecomment-537692208)], so we will need to update documentation as we deploy the update. Other features have not been tested for changes as of the writing of this issue.

To me, these are the most notable changes:

- Passing `client-id` to the CDN when loading the SDK, instead of passing `env` and `client` during the component `render()` call.
- Passing `commit` to the CDN when loading the SDK, instead of passing `commit` during the component `render()` call.
- Passing `locale` to the CDN when loading the SDK, instead of passing `locale` during the component `render()` call.
- Use vanilla JS `promise` and `fetch` instead of `paypal.Promise` and `paypal.request`. This has some implications regarding IE11 compatibility [[#](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/622#discussion_r330920096)]

<hr />

# Child issues

- [ ] Store `client-id` so we can load the new SDK (#645).
- [ ] Pass `disable-funding` and `disable-card` when we load the new SDK (#647).
- [ ] Pass `commit` when we load the new SDK (#648).
- [ ] Add polyfills for `fetch` and `Promise` (#649).
- [ ] Redirect to a cancellation page when appropriate (#650).
- [ ] Catch and handle errors that happen during the checkout flow (#651).

**Comment by mattallan** [comment]
Closed with #668 🎉
